# Generated by Django 2.2 on 2021-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('direccion', models.CharField(max_length=50, verbose_name='dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='tel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
